{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "credentials-operator.serviceAccountName" . }}
  labels:
    {{- include "credentials-operator.labels" . | nindent 4 }}
{{- end -}}
