// Code generated by main. DO NOT EDIT.

// +k8s:deepcopy-gen=package
// +groupName=credentials.mjpitz.com
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// CredentialList is a list of Credential resources
type CredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Credential `json:"items"`
}

func NewCredential(namespace, name string, obj Credential) *Credential {
	obj.APIVersion, obj.Kind = SchemeGroupVersion.WithKind("Credential").ToAPIVersionAndKind()
	obj.Name = name
	obj.Namespace = namespace
	return &obj
}
