// Code generated by main. DO NOT EDIT.

// +k8s:deepcopy-gen=package
// +groupName=credentials.mjpitz.com
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// CredentialsList is a list of Credentials resources
type CredentialsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Credentials `json:"items"`
}

func NewCredentials(namespace, name string, obj Credentials) *Credentials {
	obj.APIVersion, obj.Kind = SchemeGroupVersion.WithKind("Credentials").ToAPIVersionAndKind()
	obj.Name = name
	obj.Namespace = namespace
	return &obj
}
